[package]
name = "simdnbt-derive"
version = "0.2.1"
edition = "2021"
description = "Derive macros for simdnbt"
license = "MIT"
repository = "https://github.com/mat-1/simdnbt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.70"
quote = "1.0.33"
syn = "2.0.39"

[lib]
proc-macro = true
